export const CHANGE_MESSAGE_FC = 'CHANGE_MESSAGE_FC'
export const CHANGE_MESSAGE_BY_PARAM_FC = 'CHANGE_MESSAGE_BY_PARAM_FC'
export const USER_ADD_TO_LIST = 'user_add_to_list'
export const INCREAMENT = 'increament'
export const PRODUCT_DETAIL = 'productDetail'
export const REMOVE_PRODUCT = 'removeproduct'